#! /bin/sh
# /etc/init.d/openrover

# The following part always gets executed.

# The following part carries out specific functions depending on arguments.
case "$1" in
  start)
    echo "Starting openrover"
    start-stop-daemon --start --quiet --oknodo --chdir /home/pi/openrover --background --pidfile /var/run/openrover.pid --make-pidfile --exec /usr/bin/python /home/pi/openrover/main.py
    echo "openrover is started"
    ;;
  stop)
    echo "Stopping openrover"
    start-stop-daemon --stop --pidfile /var/run/openrover.pid
    echo "openrover is dead"
    ;;
  restart)
    echo "Starting openrover"
    start-stop-daemon --start --quiet --oknodo --chdir /home/pi/openrover --background --pidfile /var/run/openrover.pid --make-pidfile --exec /usr/bin/python /home/pi/openrover/main.py
    echo "openrover is started"
    echo "Stopping openrover"
    start-stop-daemon --stop --pidfile /var/run/openrover.pid
    echo "openrover is dead"
    ;;
  *)
    echo "Usage: /etc/init.d/openrover {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
